version: "3.9"

services:
  backend:
    build: ./LMS-Backend
    container_name: django_backend
    volumes:
      - ./LMS-Backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./LMS-Backend/.env
    depends_on:
      - mongo
    working_dir: /app
    command: gunicorn LMSBackend.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build: ./LMS-Frontend
    container_name: frontend_build
    command: ["true"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./LMS-Frontend/build:/usr/share/nginx/html
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Pratik
      MONGO_INITDB_ROOT_PASSWORD: Pratik1$
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    

volumes:
  mongo_data:
  static_volume:
  media_volume:

